import type { ColorPalletType } from '../../../types/color_pallets';
import { cn } from '../../../util/cn';

const color: Record<ColorPalletType, string> = {
    red: cn(
        'active:bg-red-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-red-150',
        'disabled:text-red-150',
        'hover:bg-red-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-red-200',
        'text-red-500',
    ),
    orange: cn(
        'active:bg-orange-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-orange-150',
        'disabled:text-orange-150',
        'hover:bg-orange-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-orange-200',
        'text-orange-500',
    ),
    yellow: cn(
        'active:bg-yellow-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-yellow-150',
        'disabled:text-yellow-150',
        'hover:bg-yellow-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-yellow-200',
        'text-yellow-500',
    ),
    lime: cn(
        'active:bg-lime-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-lime-150',
        'disabled:text-lime-150',
        'hover:bg-lime-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-lime-200',
        'text-lime-500',
    ),
    green: cn(
        'active:bg-green-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-green-150',
        'disabled:text-green-150',
        'hover:bg-green-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-green-200',
        'text-green-500',
    ),
    teal: cn(
        'active:bg-teal-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-teal-150',
        'disabled:text-teal-150',
        'hover:bg-teal-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-teal-200',
        'text-teal-500',
    ),
    cyan: cn(
        'active:bg-cyan-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-cyan-150',
        'disabled:text-cyan-150',
        'hover:bg-cyan-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-cyan-200',
        'text-cyan-500',
    ),
    blue: cn(
        'active:bg-blue-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-blue-150',
        'disabled:text-blue-150',
        'hover:bg-blue-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-blue-200',
        'text-blue-500',
    ),
    purple: cn(
        'active:bg-purple-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-purple-150',
        'disabled:text-purple-150',
        'hover:bg-purple-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-purple-200',
        'text-purple-500',
    ),
    fuchsia: cn(
        'active:bg-fuchsia-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-fuchsia-150',
        'disabled:text-fuchsia-150',
        'hover:bg-fuchsia-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-fuchsia-200',
        'text-fuchsia-500',
    ),
    pink: cn(
        'active:bg-pink-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-pink-150',
        'disabled:text-pink-150',
        'hover:bg-pink-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-pink-200',
        'text-pink-500',
    ),
    gray: cn(
        'active:bg-gray-50',
        'bg-transparent',
        'disabled:bg-transparent',
        'disabled:outline-gray-150',
        'disabled:text-gray-150',
        'hover:bg-gray-0',
        'hover:disabled:bg-transparent',
        'outline',
        'outline-gray-200',
        'text-gray-500',
    ),
};

export const btnRedOutline = color.red;
export const btnOrangeOutline = color.orange;
export const btnYellowOutline = color.yellow;
export const btnLimeOutline = color.lime;
export const btnGreenOutline = color.green;
export const btnTealOutline = color.teal;
export const btnCyanOutline = color.cyan;
export const btnBlueOutline = color.blue;
export const btnPurpleOutline = color.purple;
export const btnFuchsiaOutline = color.fuchsia;
export const btnPinkOutline = color.pink;
export const btnGrayOutline = color.gray;
