import type { ColorPalletType } from '../../../types/color_pallets';
import { cn } from '../../../util/cn';

const colors: Record<ColorPalletType, string> = {
    red: cn(
        'active:bg-red-100',
        'bg-red-0',
        'disabled:bg-red-0',
        'disabled:hover:bg-red-0',
        'disabled:outline-red-100',
        'disabled:text-red-150',
        'hover:bg-red-50',
        'outline',
        'outline-red-200',
        'text-red-500',
    ),
    orange: cn(
        'active:bg-orange-100',
        'bg-orange-0',
        'disabled:bg-orange-0',
        'disabled:hover:bg-orange-0',
        'disabled:outline-orange-100',
        'disabled:text-orange-150',
        'hover:bg-orange-50',
        'outline',
        'outline-orange-200',
        'text-orange-500',
    ),
    yellow: cn(
        'active:bg-yellow-100',
        'bg-yellow-0',
        'disabled:bg-yellow-0',
        'disabled:hover:bg-yellow-0',
        'disabled:outline-yellow-100',
        'disabled:text-yellow-150',
        'hover:bg-yellow-50',
        'outline',
        'outline-yellow-200',
        'text-yellow-500',
    ),
    lime: cn(
        'active:bg-lime-100',
        'bg-lime-0',
        'disabled:bg-lime-0',
        'disabled:hover:bg-lime-0',
        'disabled:outline-lime-100',
        'disabled:text-lime-150',
        'hover:bg-lime-50',
        'outline',
        'outline-lime-200',
        'text-lime-500',
    ),
    green: cn(
        'active:bg-green-100',
        'bg-green-0',
        'disabled:bg-green-0',
        'disabled:hover:bg-green-0',
        'disabled:outline-green-100',
        'disabled:text-green-150',
        'hover:bg-green-50',
        'outline',
        'outline-green-200',
        'text-green-500',
    ),
    teal: cn(
        'active:bg-teal-100',
        'bg-teal-0',
        'disabled:bg-teal-0',
        'disabled:hover:bg-teal-0',
        'disabled:outline-teal-100',
        'disabled:text-teal-150',
        'hover:bg-teal-50',
        'outline',
        'outline-teal-200',
        'text-teal-500',
    ),
    cyan: cn(
        'active:bg-cyan-100',
        'bg-cyan-0',
        'disabled:bg-cyan-0',
        'disabled:hover:bg-cyan-0',
        'disabled:outline-cyan-100',
        'disabled:text-cyan-150',
        'hover:bg-cyan-50',
        'outline',
        'outline-cyan-200',
        'text-cyan-500',
    ),
    blue: cn(
        'active:bg-blue-100',
        'bg-blue-0',
        'disabled:bg-blue-0',
        'disabled:hover:bg-blue-0',
        'disabled:outline-blue-100',
        'disabled:text-blue-150',
        'hover:bg-blue-50',
        'outline',
        'outline-blue-200',
        'text-blue-500',
    ),
    purple: cn(
        'active:bg-purple-100',
        'bg-purple-0',
        'disabled:bg-purple-0',
        'disabled:hover:bg-purple-0',
        'disabled:outline-purple-100',
        'disabled:text-purple-150',
        'hover:bg-purple-50',
        'outline',
        'outline-purple-200',
        'text-purple-500',
    ),
    fuchsia: cn(
        'active:bg-fuchsia-100',
        'bg-fuchsia-0',
        'disabled:bg-fuchsia-0',
        'disabled:hover:bg-fuchsia-0',
        'disabled:outline-fuchsia-100',
        'disabled:text-fuchsia-150',
        'hover:bg-fuchsia-50',
        'outline',
        'outline-fuchsia-200',
        'text-fuchsia-500',
    ),
    pink: cn(
        'active:bg-pink-100',
        'bg-pink-0',
        'disabled:bg-pink-0',
        'disabled:hover:bg-pink-0',
        'disabled:outline-pink-100',
        'disabled:text-pink-150',
        'hover:bg-pink-50',
        'outline',
        'outline-pink-200',
        'text-pink-500',
    ),
    gray: cn(
        'active:bg-gray-100',
        'bg-gray-0',
        'disabled:bg-gray-0',
        'disabled:hover:bg-gray-0',
        'disabled:outline-gray-100',
        'disabled:text-gray-150',
        'hover:bg-gray-50',
        'outline',
        'outline-gray-200',
        'text-gray-500',
    ),
};

export const btnRedSurface = colors.red;
export const btnOrangeSurface = colors.orange;
export const btnYellowSurface = colors.yellow;
export const btnLimeSurface = colors.lime;
export const btnGreenSurface = colors.green;
export const btnTealSurface = colors.teal;
export const btnCyanSurface = colors.cyan;
export const btnBlueSurface = colors.blue;
export const btnPurpleSurface = colors.purple;
export const btnFuchsiaSurface = colors.fuchsia;
export const btnPinkSurface = colors.pink;
export const btnGraySurface = colors.gray;
